name: chenron_workspace
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - apps/chenron
  - packages/basedir
  - packages/cache_manager
  - packages/vibe_core
  - packages/vibe
  - packages/web_archiver
  - packages/platform_provider
