name: chenron_workspace
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - apps/chenron
  - packages/basedir
  - packages/cache_manager
  - packages/vibe
  - packages/web_archiver
  - packages/platform_provider
  - packages/chenron_mockups
  - packages/app_logger
  - packages/core
  - packages/database
