name: vibe
description: "Theming core utilities using FlexColorScheme (FlexSchemeColor)."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  signals: ^6.0.2
  vibe_core: ^0.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
