name: basedir
description: "Directory utilities for Chenron: base directory resolution and structure management."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
