name: cache_manager
description: A caching package for handling metadata and image caching with persistence
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.4
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
