name: core
description: Shared patterns and utilities for Chenron.
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
