name: chenron_mockups
description: Test support utilities, mocks, and fixtures for Chenron
publish_to: none
version: 0.0.1
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform_provider: ^0.1.0
  cuid2: ^3.1.0
  drift: ^2.28.2
  faker: ^2.1.0
  get_it: ^8.2.0
  signals_flutter: ^6.0.2
  mockito: ^5.4.4
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  app_logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  drift_dev: ^2.28.3
